package org.generator.entities;

import jakarta.persistence.*;
import lombok.*;

import java.util.List;

/**
 * Represents a group of students within the university.
 * This entity is mapped to the "UNI_GROUPS" table in the database.
 */
@Entity
@Table(name="UNI_GROUPS")
@Data
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class Group {

    /**
     * The unique identifier for the group.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * The unique code identifying the group
     * This field cannot be null.
     */
    @Column(name = "CODE", nullable = false)
    private String code;

    /**
     * The list of students belonging to this group.
     * This establishes a many-to-many relationship with the {@link Student} entity.
     * The relationship is fetched eagerly, and operations like persist and merge
     * are cascaded to the associated students.
     * The {@link JoinTable} annotation specifies the "UNI_GROUPS_STUDENTS" intermediate table
     * used to manage this many-to-many relationship.
     * The "GROUP_ID" column in the intermediate table references the ID of this group,
     * and the "STUDENTS_ID" column references the ID of the {@link Student} entity.
     */
    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinTable(
            name = "UNI_GROUPS_STUDENTS",
            joinColumns = @JoinColumn(name = "GROUP_ID"),
            inverseJoinColumns = @JoinColumn(name = "STUDENTS_ID")
    )
    private List<Student> students;

    /**
     * The year of study for this group.
     */
    @Column(name = "YEAR")
    private Integer year;

    /**
     * The student who is the leader of this group.
     * This establishes a one-to-one relationship with the {@link Student} entity.
     * The relationship is fetched eagerly, and persist operations are cascaded.
     * The "GROUP_LEADER" column in the "UNI_GROUPS" table is a foreign key
     * referencing the "id" column of the {@link Student} table.
     */
    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.PERSIST)
    @JoinColumn(name = "GROUP_LEADER", referencedColumnName = "id")
    private Student groupLeader;
}