package org.generator.entities;

import jakarta.persistence.*;
import lombok.*;

import java.util.List;

/**
 * Represents a professor within the university.
 * This entity is mapped to the "PROFESSORS" table in the database.
 */
@Entity
@Table(name="PROFESSORS")
@Data
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class Professor {

    /**
     * The unique identifier for the professor.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * The full name of the professor.
     */
    @Column(name = "FULL_NAME")
    private String fullName;

    /**
     * A collection of courses taught by the professor.
     * This is stored as an embedded collection in the "PROFESSORS" table.
     */
    @ElementCollection
    @Column(name = "COURSES")
    private List<String> courses;

    /**
     * The email address of the professor.
     */
    @Column(name = "EMAIL")
    private String email;

    /**
     * The academic rank or title of the professor (e.g., Lecturer, Professor).
     */
    @Column(name = "RANK_TITLE")
    private String rank;
}
