package org.generator.entities;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a student within the university.
 * This entity is mapped to the "STUDENTS" table in the database.
 */
@Entity
@Table(name="STUDENTS")
@Data
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class Student {

    /**
     * The unique identifier for the student.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * The first name(s) of the student.
     */
    @Column(name = "FIRST_NAME")
    private String firstName;

    /**
     * The last name of the student.
     */
    @Column(name = "LAST_NAME")
    private String lastName;

    /**
     * The year of study for the student.
     */
    @Column(name = "YEAR")
    private Integer year;

    /**
     * The email address of the student.
     */
    @Column(name = "EMAIL")
    private String email;

    /**
     * The paternal initial(s) of the student.
     */
    @Column(name = "PATERNAL_INITIAL")
    private String paternalInitial;
}